name: ci

on:
  push:
  pull_request:

jobs:
  ci:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
        node:
          - 18.x
          - 20.x
          - 22.x

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: 'yarn'

      - name: Install
        run: |
          yarn install --frozen-lockfile --non-interactive

      - name: Linting
        run: |
          yarn grunt ci-checks
          yarn grunt validate-angular-files

      - name: Unit Testing
        run: |
          yarn grunt test:promises-aplus
          yarn grunt test:jqlite --browsers=FirefoxHeadless --reporters=spec
          yarn grunt test:modules --browsers=FirefoxHeadless --reporters=spec
          yarn grunt test:modules --browsers=FirefoxHeadless --reporters=spec
          yarn grunt test:docs --browsers=FirefoxHeadless --reporters=spec
          yarn grunt test:jquery --browsers=FirefoxHeadless --reporters=spec
          yarn grunt test:jquery-2.2 --browsers=FirefoxHeadless --reporters=spec
          yarn grunt test:jquery-2.1 --browsers=FirefoxHeadless --reporters=spec
