name: publish

on:
  release:
    types:
      - created

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          #registry-url: https://npm.pkg.github.com/
          node-version: 14.x
          cache: 'yarn'

      - name: Install
        run: |
          yarn install --frozen-lockfile --non-interactive
          yarn grunt package

      #- name: Publish to GitHub Packages
      #  run: |
      #    yarn publish
      #  env:
      #    NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Publish to NPM Registry
        run: |
          yarn publish --registry=https://registry.npmjs.org/
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
